### ISSUE TITLE
windows下如何配置使用

### ISSUE THREAD

**Issue by zerolfq** [Fishermanykx/MC-DC_Coverage_Calculating#1]
冒昧打扰，可以请教一下这个代码要在Windows下如何使用吗

**Comment by Fishermanykx** [comment]
> 冒昧打扰，可以请教一下这个代码要在Windows下如何使用吗

不好意思，这个项目还没有开发完成，如果你直接clone这个代码是没办法在Windows下运行的

**Comment by zerolfq** [comment]
在这几天Windows上学习编写llvm pass和clang插件我已经体会到了它在windows上使用的困难，所以我开始使用Linux的虚拟机开始尝试clang对于c语言插桩进行测试的学习,是否按官方文档的插件编写方法就可以运行你的代码进行mc/dc覆盖测试呢


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Fishermanykx/MC-DC_Coverage_Calculating"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年4月27日(星期二) 中午12:36
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Fishermanykx/MC-DC_Coverage_Calculating] windows下如何配置使用 (#1)





  
冒昧打扰，可以请教一下这个代码要在Windows下如何使用吗
  
不好意思，这个项目还没有开发完成，如果你直接clone这个代码是没办法在Windows下运行的

**Comment by Fishermanykx** [comment]
这个项目还没开发完成，所以还没有实现MC/DC覆盖率统计的功能，在此感到很抱歉。。。不过这个代码倒是按官方文档就可以跑通。目前我已经放弃使用clang实现MC/DC覆盖率统计而改用llvm的pass。等我开发完成之后会回复你的。

**Comment by zerolfq** [comment]
clang更难以完成吗？那我也转而使用llvm-pass进行MC/DC覆盖测试统计，非常感谢的回信对于我的疑问进行解答，巨佬可以加一个qq好友吗？


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Fishermanykx/MC-DC_Coverage_Calculating"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年4月27日(星期二) 晚上7:17
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Fishermanykx/MC-DC_Coverage_Calculating] windows下如何配置使用 (#1)





 
这个项目还没开发完成，所以还没有实现MC/DC覆盖率统计的功能，在此感到很抱歉。。。不过这个代码倒是按官方文档就可以跑通。目前我已经放弃使用clang实现MC/DC覆盖率统计而改用llvm的pass。等我开发完成之后会回复你的。

**Comment by Fishermanykx** [comment]
> clang更难以完成吗？那我也转而使用llvm-pass进行MC/DC覆盖测试统计，非常感谢的回信对于我的疑问进行解答，巨佬可以加一个qq好友吗？
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "Fishermanykx/MC-DC_Coverage_Calculating" ***@***.***&gt;; 发送时间:&nbsp;2021年4月27日(星期二) 晚上7:17 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [Fishermanykx/MC-DC_Coverage_Calculating] windows下如何配置使用 (#1) 这个项目还没开发完成，所以还没有实现MC/DC覆盖率统计的功能，在此感到很抱歉。。。不过这个代码倒是按官方文档就可以跑通。目前我已经放弃使用clang实现MC/DC覆盖率统计而改用llvm的pass。等我开发完成之后会回复你的。 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

可以把你QQ号用邮箱发给我，我的邮箱是：fishermanykx.mail@gmail.com
